spring.datasource:
    url: jdbc:mysql://localhost:3306/dbtest
    username: root
    password: root
spring.jpa:
    properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
        use-new-id-generator-mappings: false
        ddl-auto: create
    show-sql: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized    
