spring.datasource:
    url: jdbc:mysql://mysql:3306/dbtest
    username: root
spring.jpa:
    properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
        use-new-id-generator-mappings: false
        ddl-auto: update
    show-sql: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8012

