spring.datasource:
    url: jdbc:mysql://localhost:3306/dbtest
    username: apuser
    password: everywhere_duck_happened_oh_no
spring.jpa:
    properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
        use-new-id-generator-mappings: false
        ddl-auto: update
    show-sql: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized    
      
      
       
